### ISSUE TITLE
Assigning a group will result in an error.

### ISSUE THREAD

**Issue by onozaty** [onozaty/redmine_issue_assign_notice#6]
```
ActiveRecord::RecordNotFound (Couldn't find User with 'id'=6 [WHERE "users"."type" IN ('User', 'AnonymousUser')]):

plugins/redmine_issue_assign_notice/lib/redmine_issue_assign_notice/issue_hook_listener.rb:34:in `redmine_issue_assign_notice_change'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
plugins/redmine_issue_assign_notice/lib/redmine_issue_assign_notice/issue_patch.rb:26:in `save_from_issue_for_assign_notice'
app/models/issue.rb:214:in `create_or_update'
app/controllers/issues_controller.rb:588:in `block in save_issue_with_child_records'
app/controllers/issues_controller.rb:575:in `save_issue_with_child_records'
app/controllers/issues_controller.rb:172:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

**Comment by onozaty** [comment]
Fixed.
